name: Deplpoy to Vercel
on:
  push:
    branches:
      - dev

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_name:
          ["multi-tenancy-distribution-demo", "davis-miami", "schmitt-berlin"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Run deployment to vercel
        run: vercel --prod --token=$VERCEL_TOKEN --confirm --no-clipboard --name="${{ matrix.project_name }}"
